spring:
  application:
    name: db-migration

  datasource:
    url: jdbc:mysql://localhost:3306/db_migration
    username: development
    password: anton123
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none  # Flyway would handle ddl creation
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

flyway:
  enabled: true  # Enable Flyway for database migrations
  locations: classpath:db/migration  # Default location for Flyway scripts